In [1]:
%pip install numpy

In [2]:
# numpy is a fundamental library for scientific computing in python
# numpy is a module that provides a large collection of functions to perform mathematical operations on arrays

import numpy as np

In [3]:
# create arrays using numpy

## create 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# conver rows and columns
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D array
arr2 = np.array([[1,2,4,5,6], [2,3,4,5,6]])
print(arr2)
print(arr2.shape) 

[[1 2 4 5 6]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("ARRAY:\n", arr)

print("TRANSPOSE:\n", arr.T)

print("Shape:\n", arr.shape)

print("Size:\n", arr.size)

print("Data type:\n", arr.dtype)

print("Itemsize:\n", arr.itemsize)

print("Bytes:\n", arr.nbytes)

print("number of dimensions:\n", arr.ndim)

ARRAY:
 [[1 2 3]
 [4 5 6]]
TRANSPOSE:
 [[1 4]
 [2 5]
 [3 6]]
Shape:
 (2, 3)
Size:
 6
Data type:
 int64
Itemsize:
 8
Bytes:
 48
number of dimensions:
 2


In [10]:
## Numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### element wise addition
print ("Addition:\n", arr1 + arr2)

### element wise subtraction
print ("Subtraction:\n", arr1 - arr2)

### element wise multiplication
print ("Multiplication:\n", arr1 * arr2)

### element wise division
print ("Division:\n", arr1 / arr2)

Addition:
 [11 22 33 44 55]
Subtraction:
 [ -9 -18 -27 -36 -45]
Multiplication:
 [ 10  40  90 160 250]
Division:
 [0.1 0.1 0.1 0.1 0.1]


In [11]:
## Universal function
arr = np.array([2,3,4,5,6])
#square root
print("Square root:\n", np.sqrt(arr))
#exponential
print("Exponential:\n", np.exp(arr))
#logarithmic
print("Logarithmic:\n", np.log(arr))
#power
print("Power:\n", np.power(arr,2))

Square root:
 [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:
 [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Logarithmic:
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Power:
 [ 4  9 16 25 36]


In [12]:
## array slicing and indexing 
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array :\n", arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0][0])
print(arr[0:2, 2:])

1
[[3 4]
 [7 8]]


In [14]:
print (arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [15]:
## Modifying array element
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [16]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [17]:
### statistical concepts -- Normalization
## change the data to have mean 0 and standard deviation 1
data = np.array([1,2,3,4,5])

# calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize data
normalized_data = (data - mean) / std_dev
print("Normalized data:\n", normalized_data)

Normalized data:
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:\n", mean)

#standard deviation
std_dev = np.std(data)
print("Standard deviation:\n", std_dev)

#median
median = np.median(data)
print("Median:\n", median)

#variance
variance = np.var(data)
print("Variance:\n", variance)

Mean:
 5.5
Standard deviation:
 2.8722813232690143
Median:
 5.5
Variance:
 8.25


In [20]:
## logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5

data[(data>5) & (data>=8)]

array([ 8,  9, 10])